### ISSUE TITLE
0-storv2 Create auto-mgmt service for capacity pools and 0-db reservations

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/0-stor_v2#54]
# Automatic management service for capacity pools and 0-db reservations

## User Story
Create automatic management service for capacity pools and 0-db reservations

#### Tickets
- [x] Auto-topup for pools [0-storv2 #48](https://github.com/threefoldtech/0-stor_v2/issues/48) 
- [x] automatic expansion of ZDB storage containers when more storage needed. [#0-storv2 #49](https://github.com/threefoldtech/0-stor_v2/issues/49)
- [x] automatic monitoring when ZDB fails and recovery actions: cancel reservation of failed 0-db and create new reservation for recovery. [0-storv2 #50](https://github.com/threefoldtech/0-stor_v2/issues/50)
