### ISSUE TITLE
Better metadata reliability

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-stor_v2#57]
The metadata is currently not really handled well in case of node failure. There are certain improvements to be made to make this more reliable:

The following things are needed, these are similar to regular data backends:

- [x] Monitor metadata backends (#61)
- [x] Add ability to replace metadata backend in case its almost full (#62)
- [x] Add ability to reserve new metadata backend if one of the backends dies (#63)

With the above, we can then implement metadata rebuilding:

- [x] Support rebuilding from a (partial) metadata cluster to a full metadata cluster (#59)
- [x] Support live migration of metadata cluster. We can stop serving requests during this time if needed, reliability > uptime (#60)
