### ISSUE TITLE
More monitoring

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-stor_v2#58]
The current code only monitors the backend data 0-db's, and has very limited info about internal operations. We can add a lot of stuff, to give more insight in how the system behaves.

- [x] Monitoring of metadata backends (see #57 and #61)
- [x] Monitoring of capacity pools we manage (#64)
- [x] An optional monitor for 0-db-fs. An Ioctl can be used to query info from the filesystem. This is useful as 0-stor is usually deployed next to 0-db-fs as part of the qsfs stack. (#65)
- [x] Monitor the wallet balance (#67)

- [ ] More internal items, which should also help to tune the system (#66)??

**Comment by weynandkuijpers** [comment]
Sorry - closed the issue by acciddent.

**Comment by LeeSmet** [comment]
Considering the coverage which is currently available I'll close this. The added internal metrics will be kept open as a tracking issue in case debugging shows we have missing info, though I think the current metrics should be sufficient.
